Apr 12 01:02:16.22
GET
500
website-love-4gt74bwfb-demon-radios-projects.vercel.app
/
Traceback (most recent call last): File "/var/task/vc__handler__python.py", line 14, in <module> __vc_spec.loader.exec_module(__vc_module) File "<frozen importlib._bootstrap_external>", line 999, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/var/task/index.py", line 1, in <module> from app import app File "/var/task/app.py", line 3, in <module> from flask import Flask, render_template, redirect, url_for, request, flash ModuleNotFoundError: No module named 'flask' Python process exited with exit status: 1. The logs above can help with debugging the issue.
Apr 12 01:02:15.73
GET
500
website-love-4gt74bwfb-demon-radios-projects.vercel.app
/
Traceback (most recent call last): File "/var/task/vc__handler__python.py", line 14, in <module> __vc_spec.loader.exec_module(__vc_module) File "<frozen importlib._bootstrap_external>", line 999, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/var/task/index.py", line 1, in <module> from app import app File "/var/task/app.py", line 3, in <module> from flask import Flask, render_template, redirect, url_for, request, flash ModuleNotFoundError: No module named 'flask' Python process exited with exit status: 1. The logs above can help with debugging the issue.
Apr 12 01:02:15.70
GET
500
website-love-4gt74bwfb-demon-radios-projects.vercel.app
/
Traceback (most recent call last): File "/var/task/vc__handler__python.py", line 14, in <module> __vc_spec.loader.exec_module(__vc_module) File "<frozen importlib._bootstrap_external>", line 999, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/var/task/index.py", line 1, in <module> from app import app File "/var/task/app.py", line 3, in <module> from flask import Flask, render_template, redirect, url_for, request, flash ModuleNotFoundError: No module named 'flask' Python process exited with exit status: 1. The logs above can help with debugging the issue.
Apr 12 01:02:15.40
GET
500
website-love-4gt74bwfb-demon-radios-projects.vercel.app
/
Traceback (most recent call last): File "/var/task/vc__handler__python.py", line 14, in <module> __vc_spec.loader.exec_module(__vc_module) File "<frozen importlib._bootstrap_external>", line 999, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/var/task/index.py", line 1, in <module> from app import app File "/var/task/app.py", line 3, in <module> from flask import Flask, render_template, redirect, url_for, request, flash ModuleNotFoundError: No module named 'flask' Python process exited with exit status: 1. The logs above can help with debugging the issue.
Apr 12 01:02:15.03
GET
500
website-love-4gt74bwfb-demon-radios-projects.vercel.app
/
Traceback (most recent call last): File "/var/task/vc__handler__python.py", line 14, in <module> __vc_spec.loader.exec_module(__vc_module) File "<frozen importlib._bootstrap_external>", line 999, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/var/task/index.py", line 1, in <module> from app import app File "/var/task/app.py", line 3, in <module> from flask import Flask, render_template, redirect, url_for, request, flash ModuleNotFoundError: No module named 'flask' Python process exited with exit status: 1. The logs above can help with debugging the issue.
Apr 12 01:02:14.76
GET
500
website-love-4gt74bwfb-demon-radios-projects.vercel.app
/
Traceback (most recent call last): File "/var/task/vc__handler__python.py", line 14, in <module> __vc_spec.loader.exec_module(__vc_module) File "<frozen importlib._bootstrap_external>", line 999, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/var/task/index.py", line 1, in <module> from app import app File "/var/task/app.py", line 3, in <module> from flask import Flask, render_template, redirect, url_for, request, flash ModuleNotFoundError: No module named 'flask' Python process exited with exit status: 1. The logs above can help with debugging the issue.
Apr 12 01:02:14.00
GET
500
website-love-4gt74bwfb-demon-radios-projects.vercel.app
/
Traceback (most recent call last): File "/var/task/vc__handler__python.py", line 14, in <module> __vc_spec.loader.exec_module(__vc_module) File "<frozen importlib._bootstrap_external>", line 999, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/var/task/index.py", line 1, in <module> from app import app File "/var/task/app.py", line 3, in <module> from flask import Flask, render_template, redirect, url_for, request, flash ModuleNotFoundError: No module named 'flask' Python process exited with exit status: 1. The logs above can help with debugging the issue. Traceback (most recent call last): File "/var/task/vc__handler__python.py", line 14, in <module> __vc_spec.loader.exec_module(__vc_module) File "<frozen importlib._bootstrap_external>", line 999, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/var/task/index.py", line 1, in <module> from app import app File "/var/task/app.py", line 3, in <module> from flask import Flask, render_template, redirect, url_for, request, flash ModuleNotFoundError: No module named 'flask' Python process exited with exit status: 1. The logs above can help with debugging the issue.
Apr 12 01:02:13.87
GET
500
website-love-4gt74bwfb-demon-radios-projects.vercel.app
/
Traceback (most recent call last): File "/var/task/vc__handler__python.py", line 14, in <module> __vc_spec.loader.exec_module(__vc_module) File "<frozen importlib._bootstrap_external>", line 999, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/var/task/index.py", line 1, in <module> from app import app File "/var/task/app.py", line 3, in <module> from flask import Flask, render_template, redirect, url_for, request, flash ModuleNotFoundError: No module named 'flask' Python process exited with exit status: 1. The logs above can help with debugging the issue.
Apr 12 01:02:13.81
GET
500
website-love-4gt74bwfb-demon-radios-projects.vercel.app
/
Traceback (most recent call last): File "/var/task/vc__handler__python.py", line 14, in <module> __vc_spec.loader.exec_module(__vc_module) File "<frozen importlib._bootstrap_external>", line 999, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/var/task/index.py", line 1, in <module> from app import app File "/var/task/app.py", line 3, in <module> from flask import Flask, render_template, redirect, url_for, request, flash ModuleNotFoundError: No module named 'flask' Python process exited with exit status: 1. The logs above can help with debugging the issue. Traceback (most recent call last): File "/var/task/vc__handler__python.py", line 14, in <module> __vc_spec.loader.exec_module(__vc_module) File "<frozen importlib._bootstrap_external>", line 999, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/var/task/index.py", line 1, in <module> from app import app File "/var/task/app.py", line 3, in <module> from flask import Flask, render_template, redirect, url_for, request, flash ModuleNotFoundError: No module named 'flask' Python process exited with exit status: 1. The logs above can help with debugging the issue.
No more logs to show within selected timeline

Logs
1 Error

Traceback (most recent call last):
File "/var/task/vc__handler__python.py", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File "<frozen importlib._bootstrap_external>", line 999, in exec_module
File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "/var/task/index.py", line 1, in <module>
from app import app